version: '3'
services:
  app:
    image: node:14
    container_name: nestjs-app
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: yarn start:dev
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: postgres-db
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
